version: '3.8'
services:
  mongodb:
        image: 'mongo:4.4'
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'local'
            MONGO_INITDB_ROOT_PASSWORD: 'local'
            MONGO_INITDB_DATABASE: 'pfm'
        volumes:
            - 'local-mongo:/data/db'
volumes:
  local-mongo:
    driver: local